---
apiVersion: v1
kind: Service
metadata:
  name: resume-metrics
  namespace: resume
  labels:
    app: resume
spec:
  selector:
    app: resume
  ports:
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resume
  namespace: resume
  labels:
    app: resume
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: resume
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
